apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy70
  labels:
    app: autodeploy70
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1717482482042
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy70
  template:
    metadata:
      labels:
        app: autodeploy70
    spec:
      containers:
        - name: autodeploy70
          image: acrworkflow1717482482042.azurecr.io/image-workflow-1717482482042:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
