apiVersion: v1
kind: Service
metadata:
  name: autodeploy70
  namespace: namespace-workflow-1717482482042
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: autodeploy70
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000